### ISSUE TITLE
Not starting on Windows 11

### ISSUE THREAD

**Issue by vsxed** [PiotrMachowski/Home-Assistant-Taskbar-Menu#21]
Seems like the application does not start correctly on Windows 11.

Configuration seems fine, config file is created, nothing stated in the logs.

Websocket API is active in my HA setup.

When i click on the application icon, simply nothing happens

**Comment by vsxed** [comment]
Debug.exe won't start aswell.

Here's the log:

`Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found.
   at Home_Assistant_Taskbar_Menu.Views.BrowserWindow..ctor(Configuration configuration)
   at Home_Assistant_Taskbar_Menu.MainWindow..ctor(Configuration configuration, ViewConfiguration viewConfiguration) in D:\Files\Programowanie\PycharmProjects\Home Assistant\Other\Home Assistant Taskbar Menu\Home Assistant Taskbar Menu\Views\MainWindow.xaml.cs:line 40
   at Home_Assistant_Taskbar_Menu.AuthWindow.SaveButtonClick(Object sender, RoutedEventArgs e) in D:\Files\Programowanie\PycharmProjects\Home Assistant\Other\Home Assistant Taskbar Menu\Home Assistant Taskbar Menu\Views\AuthWindow.xaml.cs:line 37
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Home_Assistant_Taskbar_Menu.App.Main()

[process exited with code 3762504530]`

**Comment by PiotrMachowski** [comment]
Can you try to install [Microsoft .NET Framework 4.6.1](https://www.microsoft.com/en-us/download/details.aspx?id=49981) and check again?

**Comment by vsxed** [comment]
I used the exe installer (with admin privileges)

**Comment by PiotrMachowski** [comment]
Can you verify that all files are present? (compared to zip version)

**Comment by vsxed** [comment]
Thanks for your help so far @PiotrMachowski!

As far as i can see, the files are the same in both directories (installation vs zip).
Also tried to run the application from the unzipped version, but the errors are the same as with the installer version (also the debug variant, same exception).

Is there anything else i could do to identify the issue?

**Comment by PiotrMachowski** [comment]
Can you install [Microsoft Visual C++ 2015+](https://docs.microsoft.com/en-GB/cpp/windows/latest-supported-vc-redist?view=msvc-160#visual-studio-2015-2017-2019-and-2022) and try again?

**Comment by vsxed** [comment]
Nice!

At first it didn't work because i installed the x64 version.
After installing the x86 distributable, it now starts.

Thanks so much!

**Comment by PiotrMachowski** [comment]
Thank you for your cooperation!

**Comment by fernandex00** [comment]
Same here

**Comment by PiotrMachowski** [comment]
@fernandex00 so you got it working?

**Comment by fernandex00** [comment]
> @fernandex00 so you got it working?

No, i have the same problem, even after installing c++, the app is in the taskbar, but im not able to enter

**Comment by PiotrMachowski** [comment]
Which version have you installed?
